### ISSUE TITLE
delist not working

### ISSUE THREAD

**Issue by grahamwt** [TenGbps/ISX_BL#3]
I run and ISP that one of our ips is currently blacklisted, I have tried to delist via another IP but it wont allow and requests you delist directly from that IP. I tried direct fromthat IP but seems its blocked to get to the server.

trace from un listed IP 
traceroute 212.83.152.155
 # ADDRESS                          LOSS SENT    LAST     AVG    BEST   WORST
 1 102.177.64.41                      0%    9   2.2ms     2.6     2.1     5.4
 2 41.216.138.109                     0%    9   2.4ms     2.5     2.3     3.1
 3 105.23.225.33                      0%    8   4.6ms     2.8     2.3     4.6
 4 105.16.10.217                      0%    8 164.2ms   156.9     153   164.2
 5 105.16.9.194                       0%    8 154.7ms   155.4   154.7     156
 6 105.16.32.8                        0%    8 152.7ms     153   152.4   154.6
 7 37.49.237.111                      0%    8 174.6ms   174.7   174.4     175
 8 195.154.1.99                       0%    8 188.7ms   183.5   175.7   196.8
 9 212.83.152.155                     0%    8 175.3ms   175.6   174.7   177.6

Trace from a currently listed IP 

 traceroute 212.83.152.155
 # ADDRESS                          LOSS SENT    LAST     AVG    BEST   WORST
 1 102.177.64.41                      0%    1   2.5ms     2.5     2.5     2.5
 2 41.216.138.109                     0%    1   2.2ms     2.2     2.2     2.2
 3 105.23.225.33                      0%    1   2.3ms     2.3     2.3     2.3
 4 105.16.10.217                      0%    1   155ms     155     155     155
 5 105.16.10.198                      0%    1 167.1ms   167.1   167.1   167.1
 6 105.16.33.8                        0%    1 152.5ms   152.5   152.5   152.5
 7 37.49.237.111                      0%    1 179.3ms   179.3   179.3   179.3
 8 195.154.1.99                       0%    1   183ms     183     183     183
 9                                  100%    1 timeout
10                                  100%    1 timeout
11                                  100%    1 timeout
12                                  100%    1 timeout

so makes it impossible to delist?

**Comment by alemenke** [comment]
I've got the same issue. HTTPS requests from the listed IP seems to be blocked.
```
* connect to 212.83.152.155 port 443 failed: Connection timed out                                                                                                                 
* Failed to connect to bl.isx.fr port 443: Connection timed out                                                                                                                   
* Closing connection 0                                                                                                                                                            
curl: (7) Failed to connect to bl.isx.fr port 443: Connection timed out
```

I've also tried sending an email to the mail address shown on your website (isx.fr), but it doesn't seem like it exists. The MX responds with:
```
host mx1.oonux.net[212.83.152.151] said: 550 Unknown user
```

**Comment by grahamwt** [comment]
Yeah I tried that email address too with no luck, I have had traffic off that IP for like two weeks and the dam IP is still listed. About to change all my records as I dont think will ever be able to get delisted here.

**Comment by TenGbps** [comment]
Is because the list is apply to this web server, now this issue as fixed.

**Comment by ch3g3v4r4** [comment]
No it is not fixed in any way, delisting is impossible on your site because your API does not work and you do not clear your report logs so IP`s that have resolved their issues remain blocked even though they are not spamming any more.

I have tried delisting multiple times via your API and it refuses to delist the IP in question even though there has been no reports for this IP for over 10 days!

![image](https://user-images.githubusercontent.com/12203675/45377256-5528f880-b5fa-11e8-8d2a-1770c23a3dd8.png)

Please get serious and fix your service, you are causing people a lot of damage with this kind of irresponsible behaviour !

Either fix your API so people can delist their servers after they fix their issues, or drop the API project all together as establishing a working API seems impossible for you guys and establish a normal IP delisting form like other bigger RBL`s then you guys do!

Or maybe the best idea would be to shut down your RBL totaly, it has no use what so ever except providing false reports and inaccurate data !!!!

Hope you will fix your API properly soon!

Thanks in advance!

**Comment by ch3g3v4r4** [comment]
Thank you for the fast response and for resolving this issue quickly! 

Cheers!

**Comment by ch3g3v4r4** [comment]
I cant belive it ! again ! same issue! different server (this time it has been even longer without any reports and still not delisted) .... 
![image](https://user-images.githubusercontent.com/12203675/48567639-d738e480-e8fd-11e8-8d5d-40b53a962102.png)

Still your API is not working! What is the meaning of this!?

Its been more than a month since the last time i contacted you guys and you still havent resolved the issue!

NONE OF THE RBL IS BLACKLISTING OUR IP EXCEPT YOU!

We are a hosting company and this is one of our shared host and being irresponsible like you are and keeping us blacklisted without a proper reason is causing us a lot of damage!!!!

Delist or IP  A.S.A.P. ! ! ! !

And fix your API!!!! Or setup a email on which users can contact you with their whitelist requests!

I do not want to have to come back here ever again and write to you guys and beg you to delist our server which IS NOT SENDING ANY SPAM!!!!!

This is veryyy veryyy unprofessional.

Please respond ASAP!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by TenGbps** [comment]
Please be cool, https://exchange.xforce.ibmcloud.com/ip/79.142.68.5 (nl53.altushost.com)
This ip have host Cybercrime / Hacking website (hackersactivity.com)

**Comment by ch3g3v4r4** [comment]
![image](https://user-images.githubusercontent.com/12203675/48575079-4835c780-e911-11e8-9e38-f0ebe1e988d4.png)

IBM says this is Unsuspicious on the link you provided, also you have delisted us now which means you know that this was a mistake having our server blacklisted for so long...

Please do not tell me to be cool when you do harm to our business.

And this is the second time this is happening...

Also please do not post our public IP here!!!! I havent shared it with you for a reason!

Please edit your comment and remove our IP and hostname from it A.S.A.P to avoid harming our business further!

Very unprofessional! 

Thanks in advance!
