### ISSUE TITLE
Are you guys serious?

### ISSUE THREAD

**Issue by ch3g3v4r4** [TenGbps/ISX_BL#6]
Can you pleaseeeeeeee fix this issue already?!

Its been more than a year that your delist process does not work!

So unprofessional, i am sick and tired of contacting you on git hub every time your stupid broken service does not work!

Is it so hard to write a workign API?!

Please contact me and i will do it for you if you are so incompetent! 

FIX THIS IMMEDIATELY AND WHITELIST ALL OF OUR COMPANY IP`S PERMANENTLY!

I dont want to see any of our IP`s on your broken blacklist service ever again!

If i do, and you harm our busines like this again be sure that we will take legal action against you!

YOU CANT TEST YOUR BROKEN SERVICE AT THE EXPENSE OF OUR BUSINESS!  

You do not desirve to be in business!

More than 10 days without a report, and i still cant delist!

**Comment by ch3g3v4r4** [comment]
You guys are such a disgrace ! I cant believe the way you act and the way your service works!!!!

You are a embarrassment to the entire IT industry! 

Delist all of our IP`s which are LISTED WITH NO PROPER CAUSE ONLY WITH YOU AND YOUR API STILL DOES NOT WORK!

AFTER MORE THAN A YEAR!

You have by the end of the day to fix this, if you dont our lawyer has already prepared a lawsuit which we WILL SUBMIT!

This kind of behaviour is criminal and i will not stand for it any more!!!!! 

Either start working professionaly and legally  or suffer the conveniences!

**Comment by Cicco0** [comment]
@ch3g3v4r4 

Since there is no answer either here or on Twitter, I found a workaround.

1. Install tinyproxy on your server:
`yum install -y tinyproxy && systemctl start tinyproxy`

2. Connect from your computer to your server:
`ssh -L 8888:127.0.0.1:8888 <server-ip> -N`

3. Use proxy-settings in firefox:
Firefox => Connection Settions => Manual proxy configuration => 127.0.0.1 Port: 8888 and set mark to «Use this proxy server for all protocols»

4. Browse to the site bl.isx.fr and unlist your server
